language: python
sudo: true
python:
  - "3.5"
addons:
  apt:
    packages:
    - g++
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenblas-dev
    - python3-dev
    - enchant
    - redis-server

before_install:
  - npm install -g eslint
# Install packages
install:
  - pip install pip --upgrade
  - pip install wheel
  - travis_wait pip install -r requirements.txt || date
  - travis_wait pip install -r test-requirements.txt || date
  - python -m nltk.downloader stopwords
  - pip install codecov
  - sudo service redis-server start
script:
  - pytest -v
  - flake8 .
  - eslint .
  - ./utility applications.wsgi --config ./config/celery-test/ &
  - ./utility applications.celery --config ./config/celery-test/ &
  - sleep 5
  - ./utility test_api http://localhost:8080 --debug
after_success:
  codecov
group: stable
dist: trusty
os: linux
