language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++ gfortran liblapack-dev libopenblas-dev python3-dev myspell-pt myspell-fa myspell-en-au  myspell-en-gb myspell-en-us myspell-en-za myspell-fr 
install:
  - travis_wait pip install -r requirements.txt
script:
  - nosetests -v --with-coverage --cover-package=revscoring
