language: python
sudo: true
env:
  - DOCKER_COMPOSE_VERSION=1.17.1
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# Install packages
install:
  - docker-compose build
script:
  - docker-compose up -d
  - docker exec ores_ores-worker_1 flake8 /ores
#  - eslint .
  - docker exec ores_ores-api_1 /ores/utility test_api http://localhost:8080 --debug
  - docker exec ores_ores-worker_1 py.test /ores --cov=ores -m "not redis" -vv
after_success:
  - codecov
group: stable
dist: trusty
os: linux
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
