# Top level configuration
ores:
  score_processor: local_timeout
  wsgi:
    application_root: ""
    url_prefix: ""

# Caching options
score_caches:
  memory_lru:
    class: ores.score_caches.LRU
  local_redis:
    class: ores.score_caches.Redis
    host: localhost
    prefix: ores
    socket_timeout: 15 # seconds

# Metrics collection options
metrics_collectors:
  local_logging:
    class: ores.metrics_collectors.Logger

# Score processing options
score_processors:
  defaults:
    metrics_collector: local_logging
    scoring_contexts:
      - testwiki
  local_timeout:
    class: ores.score_processors.Timeout
    timeout: 15 # seconds
  local_celery:
    class: ores.score_processors.Celery
    BROKER_URL: redis://localhost
    BROKER_TRANSPORT_OPTIONS: {'socket_timeout': 15} # seconds
    CELERY_RESULT_BACKEND: redis://localhost
    CELERY_ACCEPT_CONTENT: ['pickle']
    CELERY_TASK_SERIALIZER: 'pickle'
    CELERY_RESULT_SERIALIZER: 'pickle'
    CELERYD_CONCURRENCY: 16
    timeout: 15 # seconds
    queue_maxsize: 100 # pending tasks

# Scoring contexts
scoring_contexts:
  testwiki:
    extractor: testwiki_offline
    scorer_models:
      revid: testwiki_revid
    precache:
      revid:
        "on": ['edit']

# Available feature extractors
extractors:
  testwiki_offline:
    class: revscoring.extractors.OfflineExtractor

# Scorer models
scorer_models:
  testwiki_revid:
    class: ores.scorer_models.RevIdScorer
    version: test version
