application_root: ""
url_prefix: ""

# Scorers
scorers:
  enwiki:
    extractor: enwiki_api
    models:
      reverted: enwiki_revert

# Cache of scores
cache:
  class: ores.cache.Redis
  host: localhost
  port: 9999
  prefix: "ores"

# Feature extractors
extractors:
  defaults:
    class: revscoring.extractors.APIExtractor
    user_agent: Object Revision Evaluation Service
  enwiki_api:
    url: http://en.wikipedia.org/w/api.php
    language: english

# Scorer models
scorer_models:
  defaults:
    class: revscoring.scorers.MLScorerModel
  enwiki_revert:
    model_file: models/enwiki.reverted.linear_svc.model

# Languages
languages:
  english:
    module: revscoring.languages.english
