# Top level configuration
ores:
  cache: local_redis
  scorers:
    - enwiki
  wsgi:
    application_root: ""
    url_prefix: ""

# Available scorers
scorers:
  enwiki:
    extractor: enwiki_api
    score_cache: local_redis
    scorer_models:
      reverted: enwiki_revert

# Available caches
score_caches:
  local_redis:
    class: ores.score_caches.Redis
    host: localhost
    port: 9999
    prefix: "ores"

# Available feature extractors
extractors:
  defaults:
    class: revscoring.extractors.APIExtractor
    user_agent: Object Revision Evaluation Service (local development)
  enwiki_api:
    url: http://en.wikipedia.org/w/api.php
    language: english

# Scorer models
scorer_models:
  defaults:
    class: revscoring.scorers.MLScorerModel
  enwiki_revert:
    model_file: models/enwiki.reverted.linear_svc.model

# Languages
languages:
  english:
    module: revscoring.languages.english
