ores:
  scoring_system: local_celery
scoring_systems:
  local_celery:
    BROKER_URL: redis://localhost
    BROKER_TRANSPORT_OPTIONS: {'socket_timeout': 15} # seconds
    CELERY_RESULT_BACKEND: redis://localhost
    CELERY_ACCEPT_CONTENT: ['pickle']
    CELERY_TASK_SERIALIZER: 'pickle'
    CELERY_RESULT_SERIALIZER: 'pickle'
    CELERYD_CONCURRENCY: 8
    CELERYD_HIJACK_ROOT_LOGGER: false
